POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName":"Vlad",
  "lastName":"Korochansiy",
  "email":"mginstsser23123213123sad@gmail.com",
  "password":"ssdsdslim2322",
  "birthday":"1993-10-22",
  "isMale":true,
  "secret":45
}